/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "secondary": "#c9c6c0",
          "surface-variant": "#39342d",
          "on-primary-container": "#7e7d7d",
          "tertiary-fixed-dim": "#d8c1c1",
          "inverse-surface": "#eae1d6",
          "outline": "#8e9192",
          "secondary-container": "#4a4945",
          "on-secondary": "#31302d",
          "primary-fixed-dim": "#c8c6c5",
          "surface-container-high": "#2e2922",
          "secondary-fixed": "#e6e2dc",
          "on-error": "#690005",
          "tertiary-fixed": "#f5dddc",
          "on-primary-fixed": "#1c1b1b",
          "surface": "#16130d",
          "on-surface-variant": "#c4c7c7",
          "inverse-on-surface": "#343028",
          "on-error-container": "#ffdad6",
          "surface-dim": "#16130d",
          "on-secondary-fixed-variant": "#484743",
          "on-secondary-fixed": "#1c1c18",
          "primary-container": "#121212",
          "tertiary": "#d8c1c1",
          "on-secondary-container": "#bbb8b2",
          "on-primary": "#313030",
          "tertiary-container": "#1b0f0f",
          "error-container": "#93000a",
          "primary-fixed": "#e5e2e1",
          "surface-container-highest": "#39342d",
          "surface-bright": "#3d3931",
          "primary": "#c8c6c5",
          "inverse-primary": "#5f5e5e",
          "error": "#ffb4ab",
          "surface-container-lowest": "#110e08",
          "on-surface": "#eae1d6",
          "secondary-fixed-dim": "#c9c6c0",
          "surface-tint": "#c8c6c5",
          "background": "#16130d",
          "on-background": "#eae1d6",
          "surface-container-low": "#1f1b14",
          "on-tertiary-container": "#8c7979",
          "on-tertiary-fixed": "#251818",
          "on-primary-fixed-variant": "#474646",
          "outline-variant": "#444748",
          "on-tertiary": "#3b2d2d",
          "on-tertiary-fixed-variant": "#534343",
          "surface-container": "#231f18"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "gutter-editorial": "2rem",
          "margin-page": "5vw",
          "stack-xl": "8rem",
          "stack-md": "1.5rem",
          "stack-lg": "4rem",
          "stack-sm": "0.5rem"
      },
      "fontFamily": {
          "accent-script": ["Parisienne", "cursive"],
          "headline-lg": ["Bodoni Moda", "serif"],
          "display-editorial": ["Bodoni Moda", "serif"],
          "body-sm": ["Inter", "sans-serif"],
          "label-caps": ["Inter", "sans-serif"],
          "body-lg": ["Libre Baskerville", "serif"],
          "headline-lg-mobile": ["Bodoni Moda", "serif"]
      },
      "fontSize": {
          "accent-script": ["32px", { "lineHeight": "100%", "fontWeight": "400" }],
          "headline-lg": ["64px", { "lineHeight": "120%", "letterSpacing": "-0.01em", "fontWeight": "400" }],
          "display-editorial": ["120px", { "lineHeight": "110%", "letterSpacing": "-0.03em", "fontWeight": "300" }],
          "body-sm": ["14px", { "lineHeight": "160%", "letterSpacing": "0.05em", "fontWeight": "400" }],
          "label-caps": ["12px", { "lineHeight": "100%", "letterSpacing": "0.2em", "fontWeight": "500" }],
          "body-lg": ["18px", { "lineHeight": "180%", "fontWeight": "400" }],
          "headline-lg-mobile": ["40px", { "lineHeight": "120%", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
